In [2]:
import numpy as np

In [3]:
x=[[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]]

In [4]:
x

[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [5]:
y=np.array(x)

In [6]:
y

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [7]:
a=[1,2,3,4,5]

In [8]:
y=[[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
x=np.array(a)

In [16]:
x.max()

5

In [17]:
x.argmax()

4

In [18]:
x=np.arange(10)

In [19]:
y=np.arange(10,20)

In [20]:
z=x+y

In [21]:
z

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [22]:
z=x/y

In [23]:
z

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [24]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [25]:
z=np.arange(11)

In [27]:
k=x+y

In [28]:
k

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])